# Generated by Django 5.0.2 on 2024-03-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questventory_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developerName', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questventory_App.developer')),
            ],
        ),
        migrations.CreateModel(
            name='GameConsoleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questventory_App.console')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questventory_App.game')),
            ],
            options={
                'unique_together': {('game', 'console')},
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('horror', 'Horror'), ('rpg', 'RPG')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='game',
            name='consoles',
            field=models.ManyToManyField(through='Questventory_App.GameConsoleStock', to='Questventory_App.console'),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='Questventory_App.genre'),
        ),
    ]
