# Generated by Django 5.0.2 on 2024-03-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questventory_App', '0002_console_developer_game_gameconsolestock_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='nationality',
        ),
        migrations.AlterField(
            model_name='console',
            name='name',
            field=models.CharField(choices=[('nintendo switch', 'Nintendo Switch'), ('sony playstation 5', 'Sony Playstation 5'), ('microsoft xbox series x', 'Microsoft Xbox Series X')], max_length=100),
        ),
    ]
