# Generated by Django 5.0.2 on 2024-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questventory_App', '0003_remove_console_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='developerName',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genreName',
        ),
        migrations.AddField(
            model_name='developer',
            name='name',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('horror', 'Horror'), ('rpg', 'RPG')], default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='console',
            name='name',
            field=models.CharField(choices=[('nintendo_switch', 'Nintendo Switch'), ('sony_playstation_5', 'Sony Playstation 5'), ('microsoft_xbox_series_x', 'Microsoft Xbox Series X')], max_length=100, unique=True),
        ),
    ]
