# Generated by Django 5.0.2 on 2024-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questventory_App', '0004_remove_developer_developername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconsolestock',
            name='is_low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
