# Generated by Django 5.0.2 on 2024-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questventory_App', '0005_gameconsolestock_is_low_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='name',
            field=models.CharField(choices=[('nintendo switch', 'Nintendo Switch'), ('sony playstation 5', 'Sony Playstation 5'), ('microsoft xbox series x', 'Microsoft Xbox Series X')], max_length=100, unique=True),
        ),
    ]
