# Generated by Django 5.0.2 on 2024-03-18 16:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questventory_App', '0006_alter_console_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('59.99'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('horror', 'Horror'), ('rpg', 'RPG'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('puzzle', 'Puzzle'), ('sports', 'Sports'), ('racing', 'Racing'), ('fighting', 'Fighting'), ('platformer', 'Platformer'), ('shooter', 'Shooter'), ('mmo', 'MMO'), ('music', 'Music/Rhythm'), ('indie', 'Indie'), ('arcade', 'Arcade'), ('visual_novel', 'Visual Novel'), ('card_game', 'Card Game'), ('educational', 'Educational'), ('sandbox', 'Sandbox'), ('battle_royale', 'Battle Royale'), ('stealth', 'Stealth')], max_length=50, unique=True),
        ),
    ]
